const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Timer,
		C3.Behaviors.Flash,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.EightDir.Exps.MovingAngle,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.EightDir.Acts.SimulateControl
	];
};
self.C3_JsPropNameTable = [
	{Vida: 0},
	{Invencivel: 0},
	{DashCooldown: 0},
	{VelAtual: 0},
	{"8Direções": 0},
	{RestritoAoLayout: 0},
	{Cronômetro: 0},
	{Piscar: 0},
	{Player: 0},
	{Angulo: 0},
	{InimigoBala: 0},
	{InimigoRico: 0},
	{InimigoPerseguidor: 0},
	{ScoreTempo: 0},
	{Teclado: 0},
	{SubTitulo: 0},
	{Mouse: 0},
	{BotaoPlay: 0},
	{GameOverFundo: 0},
	{BotaoReplay: 0},
	{BotaoSair: 0},
	{GameOverFrase: 0},
	{GameOverFrase2: 0},
	{GameOcerGatinho: 0},
	{GameOveri: 0},
	{ScoreGameOver: 0},
	{TelaPlay: 0},
	{Áudio: 0},
	{BotaoCima: 0},
	{BotaoBaixo: 0},
	{BotaoEsquerda: 0},
	{BotaoDireita: 0},
	{BotaoDash: 0},
	{Toque: 0},
	{InformaçãoDaPlataforma: 0},
	{PlanoDeFundoEmBlocos: 0},
	{BotaoMusica: 0},
	{DashPronto: 0},
	{TempoSobrevivencia: 0},
	{JogoAtivo: 0},
	{EstaMutado: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	InimigoBala: class extends self.ISpriteInstance {},
	InimigoRico: class extends self.ISpriteInstance {},
	InimigoPerseguidor: class extends self.ISpriteInstance {},
	ScoreTempo: class extends self.ITextInstance {},
	Teclado: class extends self.IInstance {},
	SubTitulo: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	BotaoPlay: class extends self.ISpriteInstance {},
	GameOverFundo: class extends self.ISpriteInstance {},
	BotaoReplay: class extends self.ISpriteInstance {},
	BotaoSair: class extends self.ISpriteInstance {},
	GameOverFrase: class extends self.ITextInstance {},
	GameOverFrase2: class extends self.ITextInstance {},
	GameOcerGatinho: class extends self.ISpriteInstance {},
	GameOveri: class extends self.ISpriteInstance {},
	ScoreGameOver: class extends self.ITextInstance {},
	TelaPlay: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	BotaoCima: class extends self.ISpriteInstance {},
	BotaoBaixo: class extends self.ISpriteInstance {},
	BotaoEsquerda: class extends self.ISpriteInstance {},
	BotaoDireita: class extends self.ISpriteInstance {},
	BotaoDash: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	InformaçãoDaPlataforma: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	BotaoMusica: class extends self.ISpriteInstance {},
	DashPronto: class extends self.ITextInstance {}
}